class CreateLaboratories < ActiveRecord::Migration
  def self.up
    create_table :laboratories do |t|
      t.date :date
      t.string :hemoglobina
      t.string :hematocrito
      t.string :cmhc
      t.string :leucocitos
      t.string :cuenta_diferencial
      t.string :linfocitos
      t.string :monocitos
      t.string :eosinofilos
      t.string :basofilos
      t.string :neut_segmen
      t.string :neut_banda
      t.string :alteraciones
      t.string :reticulocitos
      t.string :plaquetas
      t.string :sed_globular
      t.string :grupo_sanguineo
      t.string :factor_rh
      t.string :t_protrombina
      t.string :t_parcial_tromb
      t.string :quimica_sanguinea_glucosa
      t.string :hb_glicosilada
      t.string :urea
      t.string :acido_urico
      t.string :creatinina
      t.string :colesterol_total
      t.string :trigliceridos
      t.string :hdl
      t.string :ldl
      t.string :bilirrubina_total
      t.string :bilirubina_directa
      t.string :bilirrubina_indirecta
      t.string :alat_tgp
      t.string :asat_tgo
      t.string :f_alcalina
      t.string :vdrl
      t.string :antiestreptolisinas
      t.string :factor_reumatoide
      t.string :proteina_c_reactiva
      t.string :prueba_embarazo
      t.string :inmunologia_otros
      t.string :coproparasitoscopico1
      t.string :coproparasitoscopico2
      t.string :coproparasitoscopico3
      t.string :fisico_quimico
      t.string :color
      t.string :ph
      t.string :densidad
      t.string :urianalisis_glucosa
      t.string :cetona
      t.string :proteina
      t.string :nitrito
      t.string :bilirrubina
      t.string :urianalisis_hemoglobina
      t.string :sedimento
      t.string :urobilinogeno
      t.string :urianalisisis_leucocitos
      t.string :eritrocitos
      t.string :cel_epiteliales
      t.string :bacterias
      t.string :cristales
      t.string :cilindros
      t.string :exudado_gram
      t.string :basiloscopia_baar1
      t.string :basiloscopia_baar2
      t.string :basiloscopia_baar3
      t.string :cultivo
      t.string :microbiologia_otros
      t.string :tolerancia_glucosa_ayuno
      t.string :tolerancia_glucosa_1hora
      t.string :tolerancia_glucosa_2horas
      t.string :tolerancia_glucosa_observaciones


      t.boolean :hemoglobina_reactivo
      t.boolean :hematocrito_reactivo
      t.boolean :cmhc_reactivo
      t.boolean :leucocitos_reactivo
      t.boolean :cuenta_diferencial_reactivo
      t.boolean :linfocitos_reactivo
      t.boolean :monocitos_reactivo
      t.boolean :eosinofilos_reactivo
      t.boolean :basofilos_reactivo
      t.boolean :neut_segmen_reactivo
      t.boolean :neut_banda_reactivo
      t.boolean :reticulocitos_reactivo
      t.boolean :plaquetas_reactivo
      t.boolean :sed_globular_reactivo
      t.boolean :grupo_sanguineo_reactivo
      t.boolean :factor_rh_reactivo
      t.boolean :t_protrombina_reactivo
      t.boolean :t_parcial_tromb_reactivo
      t.boolean :quimica_sanguinea_glucosa_reactivo
      t.boolean :hb_glicosilada_reactivo
      t.boolean :urea_reactivo
      t.boolean :acido_urico_reactivo
      t.boolean :creatinina_reactivo
      t.boolean :colesterol_total_reactivo
      t.boolean :trigliceridos_reactivo
      t.boolean :hdl_reactivo
      t.boolean :ldl_reactivo
      t.boolean :bilirrubina_total_reactivo
      t.boolean :bilirubina_directa_reactivo
      t.boolean :bilirrubina_indirecta_reactivo
      t.boolean :alat_tgp_reactivo
      t.boolean :asat_tgo_reactivo
      t.boolean :f_alcalina_reactivo
      t.boolean :vdrl_reactivo
      t.boolean :antiestreptolisinas_reactivo
      t.boolean :factor_reumatoide_reactivo
      t.boolean :proteina_c_reactiva_reactivo
      t.boolean :prueba_embarazo_reactivo
      t.boolean :coproparasitoscopico1_reactivo
      t.boolean :coproparasitoscopico2_reactivo
      t.boolean :coproparasitoscopico3_reactivo
      t.boolean :fisico_quimico_reactivo
      t.boolean :color_reactivo_reactivo
      t.boolean :ph_reactivo
      t.boolean :densidad_reactivo
      t.boolean :urianalisis_glucosa_reactivo
      t.boolean :cetona_reactivo
      t.boolean :proteina_reactivo
      t.boolean :nitrito_reactivo
      t.boolean :bilirrubina_reactivo
      t.boolean :urianalisis_hemoglobina_reactivo
      t.boolean :sedimento_reactivo
      t.boolean :urobilinogeno_reactivo
      t.boolean :urianalisisis_leucocitos_reactivo
      t.boolean :eritrocitos_reactivo
      t.boolean :cel_epiteliales_reactivo
      t.boolean :bacterias_reactivo
      t.boolean :cristales_reactivo
      t.boolean :cilindros_reactivo
      t.boolean :exudado_gram_reactivo
      t.boolean :basiloscopia_baar1_reactivo
      t.boolean :basiloscopia_baar2_reactivo
      t.boolean :basiloscopia_baar3_reactivo
      t.boolean :cultivo_reactivo
      t.boolean :tolerancia_glucosa_ayuno_reactivo
      t.boolean :tolerancia_glucosa_1hora_reactivo
      t.boolean :tolerancia_glucosa_2horas_reactivo


      t.string :num_registro
      t.string :nombre
      t.date :fecha_reporte

      t.timestamps
    end
  end

  def self.down
    drop_table :laboratories
  end
end
