class CreateClinicalHistories < ActiveRecord::Migration
  def self.up
    create_table :clinical_histories do |t|
      t.string :responsible_family
      t.string :relationship
      t.boolean :cardiovascular_mother
      t.boolean :cardiovascular_father
      t.boolean :cardiovascular_children
      t.boolean :cardiovascular_brothers
      t.boolean :cardiovascular_husband
      t.string :cardiovascular_others
      t.boolean :diabetes_mother
      t.boolean :diabetes_father
      t.boolean :diabetes_children
      t.boolean :diabetes_brothers
      t.boolean :diabetes_husband
      t.string :diabetes_others
      t.boolean :neoplastic_mother
      t.boolean :neoplastic_father
      t.boolean :neoplastic_children
      t.boolean :neoplastic_brothers
      t.boolean :neoplastic_husband
      t.string :neoplastic_others
      t.boolean :infectious_mother
      t.boolean :infectious_father
      t.boolean :infectious_children
      t.boolean :infectious_brothers
      t.boolean :infectious_husband
      t.string :infectious_others
      t.boolean :toxicomanias_mother
      t.boolean :toxicomanias_father
      t.boolean :toxicomanias_children
      t.boolean :toxicomanias_brothers
      t.boolean :toxicomanias_husband
      t.string :toxicomanias_others
      t.boolean :malformed_mother
      t.boolean :malformed_father
      t.boolean :malformed_children
      t.boolean :malformed_brothers
      t.boolean :malformed_husband
      t.string :malformed_others
      t.integer :feed
      t.boolean :vitamins
      t.boolean :iron
      t.boolean :folic_acid
      t.boolean :caffeine
      t.boolean :drugs
      t.boolean :medicaments
      t.string :medicaments_details
      t.integer :alcoholism
      t.integer :smoking
      t.boolean :toxina_tetanica_1
      t.boolean :toxina_tetanica_2
      t.boolean :influenza_h1n1
      t.boolean :influenza_estacional
      t.boolean :hipertension
      t.boolean :cardiopatia
      t.boolean :hiperlipidemia
      t.boolean :enfermedad_renal
      t.boolean :neurologicas_epilepsia
      t.boolean :psiquiatricas_depresion
      t.boolean :enfermedad_hepatica
      t.boolean :varices_flebitis
      t.boolean :funcion_tiroidea
      t.boolean :traumatismo
      t.boolean :diabetes
      t.boolean :cancer
      t.boolean :infecciosos
      t.boolean :neumopatias_asma
      t.boolean :alergias
      t.boolean :mamas
      t.boolean :cirugia_genecologica
      t.boolean :cirugias_generales
      t.boolean :complicaciones_anestesicas
      t.boolean :inmunizaciones
      t.boolean :anomalias_uterinas
      t.boolean :infertilidad
      t.boolean :transplantes
      t.boolean :geneticos
      t.integer :menarquia
      t.integer :patron_menstrual
      t.date :fum
      t.boolean :ivsa
      t.boolean :papanicolau
      t.string :papanicolau_method
      t.integer :gesta
      t.integer :partos
      t.integer :cesareas
      t.integer :abortos
      t.integer :ectopicos
      t.integer :molas
      t.date :fecha_probable_parto
      t.integer :altura_fondo_uterino
      t.integer :num_fetos
      t.integer :fcf
      t.boolean :ritmico
      t.boolean :no_audible
      t.string :grupo_rh
      t.boolean :gammaglobulina
      t.boolean :hidrops_feta
      t.boolean :anticuerpos_irregulares
      t.float :peso_anterior
      t.text :comentarios
      t.integer :diastolica
      t.integer :sistolica
      t.float :temperatura
      t.float :peso
      t.float :talla
      t.float :masa_corporal
      t.integer :cervix
      t.boolean :fluidos
      t.boolean :sangrado
      t.boolean :dilatacion
      t.boolean :borramientos
      t.boolean :reblandecimientos
      t.boolean :inicio_acido_folico
      t.boolean :inicio_multivitaminas
      t.boolean :inicio_suplementos
      t.boolean :inicio_hierro
      t.boolean :inicio_aspirina
      t.integer :patient_id
      t.integer :user_id
      t.integer :dependency_id

      t.timestamps
    end
  end

  def self.down
    drop_table :clinical_histories
  end
end
